### PR TITLE
Release 0.15.0

### PR DESCRIPTION
**Pull request by selaux**

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Looks like the list markup was wrong. I think a newline is missing before their start.

**Comment by lynxlynxlynx** [comment]
Hmm, actually it's not that simple.
On github it's fine: https://github.com/ja2-stracciatella/ja2-stracciatella.github.io/blob/master/_posts/2016-05-23-release-0.15.0.md
But not on the live site: http://ja2-stracciatella.github.io/news/

**Comment by lynxlynxlynx** [comment]
I did a quickfix, but managed to only fix the linking. Seems that jekyll is eating up the newlines for some reason.

**Comment by selaux** [comment]
Fixed by using `-` instead of `*` for lists :warning:.

**Comment by lynxlynxlynx** [comment]
That's odd, were they a different dash variant before? Because I changed them to \* just to see if it would help. My bet is on the intro newlines.

**Pull request merged**
